name: Deploy Backend Image to ECR

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual ECR deployment"
        required: true
        default: "Manual deployment"

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: watermarking-backend-repo
  AWS_ACCOUNT_ID: 995423076159

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          # Navigate into the backend directory
          cd watermark-backend/ 
          
          # 1. Build the Docker image
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          
          # 2. Tag the image with the full ECR path
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          # 3. Push the image to ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG