name: Deploy Frontend to S3 (watermarking-data-security-lmu)

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for deployment"
        required: true
        default: "Manual deployment"
      fargate_ip_endpoint:
        description: "Live Fargate API Endpoint (e.g., http://3.79.40.136:8000)"
        required: true
        default: "http://localhost:8000"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies and build
        run: |
          cd watermark-app/
          npm install
          # Uses the input parameter to set the VITE environment variable
          VITE_API_BASE_URL=${{ github.event.inputs.fargate_ip_endpoint }} npm run build
        env:
          CI: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3 Static Hosting
        run: |
          aws s3 sync watermark-app/dist s3://${{ secrets.AWS_S3_BUCKET }} --delete

      - name: Invalidate CloudFront Cache
        run: |
          echo "Invalidating CloudFront Distribution E7RFPKF6E67X1"
          aws cloudfront create-invalidation \
            --distribution-id E7RFPKF6E67X1 \
            --paths "/*"
